name: Pylint Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint==3.2.7 astroid==3.2.4 pylint-django

      - name: Run Pylint
        run: |
          echo "🧹 Проверка стиля кода..."
          if [ -f .pylintrc ]; then
            pylint $(git ls-files '*.py')
          else
            pylint --exit-zero $(git ls-files '*.py')
          fi


